OUT_DIR = build
DOC_DIR = docs

JFLAGS_DELIMETER = :
PATH_SEP = /
ifeq ($(OS),Windows_NT)
	JFLAGS_DELIMETER = ;
	RM = del
	PATH_SEP = \\
endif

JCFLAGS = -g -d ${OUT_DIR}
JC = javac
JFLAGS = -cp ".${PATH_SEP}${OUT_DIR}${JFLAGS_DELIMETER}.${PATH_SEP}postgresql-42.2.8.jar"
JVM = java
JDOC = javadoc
DFLAGS = -d ${DOC_DIR}

ENTRY_POINT = StartPage
DB_INIT_EP = DatabaseInitialize

BACKEND_DIR = BackEnd
FRONTEND_DIR = FrontEnd
DB_INIT_DIR = DatabaseTool

BACKEND_FILES = $(wildcard ${BACKEND_DIR}${PATH_SEP}*.java)
FRONTEND_FILES = $(wildcard ${FRONTEND_DIR}${PATH_SEP}*.java)
TOPLEVEL_FILES = $(wildcard *.java)
DB_INIT_FILES = $(wildcard ${DB_INIT_DIR}${PATH_SEP}*.java)

ALL_FILES = ${BACKEND_FILES} ${FRONTEND_FILES} ${TOPLEVEL_FILES}

RUN: CLEAN BUILD
	${JVM} ${JFLAGS} ${ENTRY_POINT}

BUILD: CLEAN
	${JC} ${JCFLAGS} ${ALL_FILES}

DBINIT: CLEAN DBINIT_BUILD
	${JVM} ${JCFLAGS} ${DB_INIT_EP}

DBINIT_BUILD: CLEAN
	${JC} ${JFLAGS} ${DB_INIT_FILES}

CLEAN:
	${RM} ${OUT_DIR}${PATH_SEP}*.class

DOCS: 
	${JDOC} ${DFLAGS} ${ALL_FILES}